// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieSubmissionContext))]
    [Migration("20230213164455_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.SubmitMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Romantic Comedy",
                            Director = "Nora Ephron",
                            Edited = false,
                            Rating = "PG",
                            ReleaseYear = 1998,
                            Title = "You've Got Mail"
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Drama",
                            Director = "Luca Guadagnino",
                            Edited = false,
                            Rating = "R",
                            ReleaseYear = 2017,
                            Title = "Call Me By Your Name"
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Romantic Comedy",
                            Director = "Jon Turteltaub",
                            Edited = false,
                            Rating = "PG",
                            ReleaseYear = 1995,
                            Title = "While You Were Sleeping"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
